### ISSUE TITLE
QUDT OM UO alignment

### ISSUE THREAD

**Issue by kaiiam** [kaiiam/UO_revamp#1]
@HajoRijgersberg @dr-shorthair @jamesaoverton @cmungall @SLvanL @ddooley

Continuing the discussion from https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1341#issuecomment-759719093 per @jamesaoverton to continue the conversation elsewhere and @dr-shorthair request to keep it open as a github issue. We can change to another location if desired. 

The long and short is that I'm leading the effort to revamp UO for OBO's purposes, as well as map it out to OM and QUDT. The OM folks requested to join OBO but since UO is already OBO's Unit ontology which most importantly is aligned with PATO, OM itself doesn't quite fit with the [OBO scope principles](http://obofoundry.org/principles/fp-005-delineated-content.html). 

That being said OM and QUDT are fantastic resources which are more mature an more widely used than UO. Although the harder work would be aligning them with PATO's qualities (to really be OBO compliant), what I propose here (and have [already a start on](https://github.com/kaiiam/UO_revamp/tree/main/mapping)) is to map the UO unit terms out to OM and QUDT.

For more information see this [presentation](https://drive.google.com/file/d/1vM-BtKB28jPmags8lrAO-dnfSBjzmYtH/view?usp=sharing), and  accompanying [google drive folder](https://drive.google.com/drive/folders/1tAWTNofQ_0O5TUM-zfOxX_nYRQ-jS3ut?usp=sharing).

Love to get more feedback especially from @HajoRijgersberg and @dr-shorthair. Perhaps we can even arrange a future meeting.

Cheers,
Kai

**Comment by dr-shorthair** [comment]
> what I propose here (and have already a start on) is to map the UO unit terms out to OM and QUDT.

Yes - that makes the most sense in the short term at least. Absolutely agree that this is the best way forward.

**Comment by HajoRijgersberg** [comment]
First of all, sorry for my late reply. Times have been very busy and I'm trying to catch up now.

Agree with the strategy you propose. On the other hand, we (of OM) are willing to incorporate UO relations in OM. So maybe that gives opportunities. But that is more for the long term, I guess.
On the other hand, I think you will revamp UO such, such that it will be better than OM and QUDT! :)

Cheers, Hajo

**Comment by kaiiam** [comment]
No worries @HajoRijgersberg. These are just proposals for what could be moving forward. I'm open to all ideas here and want it to be an open transparent community-agreed upon solution. Hopefully we can converge on something that takes the best parts from all the systems, or at least bridges between them.

**Comment by HajoRijgersberg** [comment]
No, not worried at all! :) I think you're doing a great job; UO will be really improved/revamped. I have all the confidence in that and that's a real good thing! :)
I'm only worried about the opaque URIs...

**Comment by kaiiam** [comment]
Lets discuss that on today's call.
