### ISSUE TITLE
Definition of 'are' is incorrect

### ISSUE THREAD

**Issue by dr-shorthair** [kaiiam/UO_revamp#14]
in https://github.com/kaiiam/UO_revamp/blob/main/nc_name_script/output/production/working_output.ttl#L6498 you have "equal to 10⁴ square metre". This is incorrect. 1 are is 100 square metres.

**Comment by kaiiam** [comment]
Much obliged @dr-shorthair I'll fix this issue. The data table the script uses including the definitions, synonyms and other annotation properties for the base units can be found [here](https://docs.google.com/spreadsheets/d/1AlKZIauwtQNg49ujaoD4OL_kTs1Is0-NlEqTvoR2a_o/edit?usp=sharing) I really appreciate the review, and as we fill in the 310 base UCUM terms I'd love to get your feedback (time allowing @dr-shorthair) as well as @handemcginty who has agreed to help with definitions and possibly also @ddooley given his time availability.

**Comment by kaiiam** [comment]
I see the mistake I took the definition from `hectare` not `are`:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/12255688/118469576-1d0cd880-b706-11eb-8495-e2d2c24ff478.png">

Thanks again @dr-shorthair!

**Comment by kaiiam** [comment]
Fixed in the UCUM google sheet table will get pulled down into the code base soon.
