### ISSUE TITLE
Create QName processing script

### ISSUE THREAD

**Issue by kaiiam** [kaiiam/UO_revamp#2]
Suggestion from @jamesaoverton to create a Python script to take a QNames string, see [QNames for Units](https://docs.google.com/spreadsheets/d/168O2bqDc9X8tQG_cZSKO5WziPUGbyH5PHFxEushnCy8/edit?usp=sharing) and return some Turtle with annotations and links to UO, OM, QUDT, UCUM.

> I'm thinking that the core would be a function with one string as its argument, e.g. `m.s-1` , that returns a Turtle string. First it would parse the string. Then I would have tables for UO, OM, QUDT, so I could look up the unit in each of those. Then I would also try to translate to UCUM. Then I would build the Turtle string and return it.

The output ttl string from the input `m.s-1` would be something like `http://purl.obolibrary.org/obo/unit_m.s-1` @jamesaoverton is this correct? With matches to 

UO: UO:0000094 `meter per second`

OM: `metre per second` http://www.ontology-of-units-of-measure.org/resource/om-2/metrePerSecond-Time

QUDT: `Meter per Second` http://qudt.org/vocab/unit/M-PER-SEC

UCUM codes: `m.s-1` and `m/s`

**Comment by jamesaoverton** [comment]
Yes. I was thinking of Turtle like this:

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix unit: <http://purl.obolibrary.org/obo/unit_> .
@prefix UO: <http://purl.obolibrary.org/obo/UO_> .
@prefix OM: <http://www.ontology-of-units-of-measure.org/resource/om-2/> .
@prefix QUDT_unit: <http://qudt.org/vocab/unit/> .

unit:m.s-1
  rdfs:label "meter per second"@en ;
  unit:abbreviation "m/s" ;
  rdfs:seeAlso UO:0000094 ;
  rdfs:seeAlso OM:meterPerSecond-Time ;
  rdfs:seeAlso QUDT_unit:M-PER-SEC ;
  unit:ucum_code "m/s" .
```

The key thing I want to show is that this is valid Turtle, and the links to various systems.

All of those predicates are up for discussion, so are some of the namespaces, and there should be more content. It should also have an `rdf:type` but again I'm not sure which it should be. But this is a start.

**Comment by HajoRijgersberg** [comment]
Thanx, good proposal! :)
But I would recommend not use unit symbols in the IRI; unit symbols are not fully unique.
And a small thing: officially 'meter' should be 'metre'. (I'm no native English speaker, but this is what I have understood from the NIST standard, based on the ISO standard.)

**Comment by HajoRijgersberg** [comment]
Unit names also aren't fully unique by the way, but they can be disambiguated by adding e.g. '(time)' in 'second (time). Since we also have a 'second (angle)'. In OM I translated that to an IRI of 'second-Time', the dash representing the brackets and Time in camel case. But perhaps better formats can be used here.

**Comment by kaiiam** [comment]
Yes this should consider using some practices already established in QUDT/OM IRIs.

**Comment by jamesaoverton** [comment]
UCUM uses abbreviated units and manages to avoid ambiguity.

**Comment by kaiiam** [comment]
First pass is in see example output when given `m.s-1`,`m.s-2`,`us`,`A/m` as inputs. Need to validate input strings to make sure they are correct [QNames](https://en.wikipedia.org/wiki/QName), e.g. `A/m` is not so it should write convert to and write out `unit:A.m-1` instead.

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix unit: <http://purl.obolibrary.org/obo/unit_> .
@prefix UO: <http://purl.obolibrary.org/obo/UO_> .
@prefix OM: <http://www.ontology-of-units-of-measure.org/resource/om-2/> .
@prefix QUDT: <http://qudt.org/vocab/unit/> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .

unit:m.s-1
  skos:exactMatch QUDT:M-PER-SEC ;
  skos:exactMatch OM:metrePerSecond-Time ;
  skos:exactMatch UO:0000094 ;
  unit:ucum_code "m/s" ;
  unit:ucum_code "m.s-1" .

unit:m.s-2
  skos:exactMatch QUDT:M-PER-SEC2 ;
  skos:exactMatch OM:metrePerSecond-TimeSquared ;
  unit:ucum_code "m/s2" ;
  unit:ucum_code "m.s-2" .

unit:us
  skos:exactMatch QUDT:MicroSEC ;
  skos:exactMatch OM:microsecond-Time ;
  skos:exactMatch UO:0000029 ;
  unit:ucum_code "us" .

unit:A/m
  skos:exactMatch QUDT:A-PER-M ;
  skos:exactMatch OM:amperePerMetre ;
  unit:ucum_code "A/m" ;
  unit:ucum_code "A.m-1" .

```

**Comment by kaiiam** [comment]
@HajoRijgersberg @jamesaoverton @dr-shorthair @cmungall @mpsaloha

Some updates here I've done full mappings of UO and OBOE to UCUM strings (following the way it was done for QUDT/OM) and integrated them into this backend script for an exchange server. I've also added code to generate English labels based on the qname strings

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/12255688/110433161-65799b80-80b0-11eb-9f7e-affab4325aa6.png">

**Comment by dr-shorthair** [comment]
Good. That's what I was hoping to see (but wasn't competent enough myself to implement :-D )

**Comment by kaiiam** [comment]
Great glad to see that you @dr-shorthair are on the same page as @jamesaoverton and myself. This was based on our understanding of what we though you were suggesting. 

Note we make use of Qname strings rather than UCUM codes both as not to violate the UCUM usage license and to ensure valide ttl. For metric terms Qname and UCUM will look quite similar but for imperial units or others with special characters they will be different, e.g. UCUM `%` vs QName `PCT`. I'm maintaining a mapping of this [here](https://github.com/kaiiam/UO_revamp/blob/main/qname_processing/input_mappings/QName/qname_labels.csv). 

This work will most likely be under a CC0 license (anyone can do anything with it) and everyone's feedback and contributions are welcome.

**Comment by dr-shorthair** [comment]
I have clarified the intention of the UCUM license: the primary concern is to prohibit forks of the actual specification document (i.e. the HTML document). Mentioning UCUM codes in applications is _encouraged_, in fact it is the whole point. 

I am trying to get them to formalise this by adopting a CC BY-ND license, with a clarifying gloss explaining that the 'ND' bit applies to the document, and the 'BY' bit is expected to be achieved through documentation of the application, not on each occurrence of a UCUM code. So you do not need to shy away from using the UCUM strings as keys, if it is convenient to do so. 

See https://ucum.org/trac/ticket/5778#comment:6

**Comment by kaiiam** [comment]
Thanks @dr-shorthair for clarifying. I know that the license was a real source of concern for @jamesaoverton. To be clear what we're doing here is not a violation of UCUM's license or there's still room for interpretation of it being such? I have very little legal expertise. I.e. untill adoption of the CC BY-ND license aren't we all QUDT/OM/this work in potential violation by using the codes?

**Comment by dr-shorthair** [comment]
You will not be chased by anyone from UCUM. Your proposed usage is exactly what they want. That's why I asked specifically about these applications, and also proposed how to clean up the license. Like I said, the only thing they actually don't want to see is a fork of the specification document. 

(UCUM dates back to before CC and the mass of work on open licenses, so they inherited a complicated bespoke license from LOINC and then fiddled with it still further. I understand that lawyers were not even involved, so it is health/computer people's hack, which looks much more fierce now than was ever the intention.)

**Comment by kaiiam** [comment]
Thanks @dr-shorthair for clarifying! I'm happy with that answer. @jamesaoverton does this quell your concerns? We can pick this discussion up in our upcoming meeting.

**Comment by HajoRijgersberg** [comment]
Hey people, it was nice talking to you yesterday! Once again, great work you have done, my compliments! :)
Just quickly on the URIs: when using the names we will have troubles with ambiguity (e.g. second, minute) and when using the symbols too... : 'a' is the symbol for 'year', but also for the SI unit 'are' (a unit for area). So all combinations with prefixes can be interpreted in two ways too, e.g. 'ha' for hectoyear or hectare. Moreover, 'Pa' can have three meanings: pascal, petaare (i.e., both SI units), and petayear. Since our ontologies and services are broader than the SI, we need to deal with this. More exotic examples: 'min' for minute and milliinch, and 'cd' for candela and centiday).
It may all sound exotic, but perhaps it isn't. Especially combinations with years are easily made. Yes, the symbol 'a' for year may not be that often used, but if we demand the use of symbols in the URIs, it may.
So I'm asking ourselves to think it over once again and hopefully we can come up with 100% non-ambiguous rules for URI creation. Hope you don't mind this discussion! :)

**Comment by jamesaoverton** [comment]
I believe that UCUM has done the work to resolve these ambiguities. I want to build on that work.

I tried your examples in this tool: https://ucum.nlm.nih.gov/ucum-lhc/demo.html

UCUM does not allow prefixes for non-SI units, so to get 'petayear', 'centiday', and 'milliinch' you can multiply by a factor.

UCUM | comment
---|---
a | year
ar | are (area)
har | hectare (hecto-are)
Pa | pascal
Par | petaare
10*15.a | petayear
min | minute
[in_i] | inch
10*-3.[in_i] | milliinch
cd | candella
10*-2.d | centiday

**Comment by HajoRijgersberg** [comment]
Yes, I understand that UCUM tackles it, but that is not in accordance with the SI... :/   The symbol 'ar' is not SI. In Europe e.g., 'ca' and 'ha' are the most commonly used units for area.
The use of numbers does not solve the problem: e.g. 10\*15.a is 10\*15 are in SI.
Couldn't we do something with disambiguation, adding some info behind the symbol if necessary, like the full name of a unit?
But thanx for the effort and the discussion! :)

**Comment by HajoRijgersberg** [comment]
For clarification, the unit 'a' is not often used, presumably because 'are' is such a short word. But 'ca' and 'ha' are.
But I'm afraid that doesn't mean that we could reserve 'a' for year' and 'ca' and 'ha' for centiare and hectare, because of the aforementioned ambiguity problems...

**Comment by kaiiam** [comment]
> UCUM does not allow prefixes for non-SI units, so to get 'petayear', 'centiday', and 'milliinch' you can multiply by a factor.

There exist some units which are not SI but do use metric prefixes, e.g., `millicurie`. Shouldn't we allow for these to use metric prefixes? Unless we thinks more important to have 100% convertibility back and forth between UCUM and the new system. 

I'm not sure if we want the latter, especially regarding "annotations" in {}. From the [UCUM-Codes-v1.4.pdf](https://ucum.nlm.nih.gov/example-UCUM-Codes-v1.4.pdf) they write:

> Strings that are often included in units of measure but are adornments for human reading and that are not formally units of measure are enclosed in curlicue brackets {}. For example, mg/mol{creat} means milligram per mole of creatinine.

If I'm understanding this correctly, the UCUM data model allows for people to encode both the unit (e.g., mg/mol) and the data type (e.g., creatinine), which I'm not sure sure if we want to support as it overlaps with the "type" specified by another ontology e.g., `CHEBI:creatinine` using an "annotation" in {} brackets. It also says that "the curlicue brackets aren’t a formal part of UCUM. This seems to be echoed in the [UCUM main page](https://ucum.org/ucum.html).

> §6 curly braces       ■1 The full range of characters 33–126 can be used within a pair of curly braces (‘{’ and ‘}’). The material enclosed in curly braces is called annotation.   ■2 Annotations do not contribute to the semantics of the unit but are meaningless by definition. Therefore, any fully conformant parser must discard all annotations.

Maybe we don't need to support this? At least not at first? Or is the above saying that parsers (such as we're building) shouldn't use UCUM:annotations anyway? Thoughts?

To @HajoRijgersberg's point:

> The symbol 'ar' is not SI. In Europe e.g., 'ca' and 'ha' are the most commonly used units for area.

Perhaps we can add some sort of annotation property for "unit symbols" e.g., 'ca' or 'ha' to a base term such as `are`. Perhaps we can pull these from mapped QUDT/OM terms?

**Comment by kaiiam** [comment]
In conversation with @jamesaoverton we're thinking of breaking it down into 4 stages: 

1) SI only. Making use of the SI brochure for codes, not the UCUM codes. E.g., `ha` would evaluate to (Hecto)(Are)

2) SI/UCUM bridge. This includes UCUM's metric units `ha` would evaluate to (Hecto)(Year)

3) UCUM simple non metric uses. This would include imperial named units e.g. things in [] like `[lb_av]`. This would follow UCUM rules. @jamesaoverton has some `_` rules to deal with []s. 

4) UCUM annotations with {} e.g. `mg/mol{creat}`. This might be a little harder to finish as we'd want to figure out the best ways of linking annotation e.g. {creat} to ontology terms. Some will be straight CHEBI/COB/other OBO mappings, but some may not yet exist (e.g., concentration of lead in blood). TBD if UO would still be the right place to host terms like `mg/mol{creat}`. 

@jamesaoverton 's though on disambiguating SI from UCUM would be to have 1) the pure SI units have a different namespace than the UCUM derived terms in stages 2-4). 

Finally, the names space for this project is still up for discussion if it's to be in OBO's namespace or WC3 etc.

**Comment by dr-shorthair** [comment]
Do you mean [w3id.org](https://w3id.org/) namespace? (W3C is only available for W3C projects, and they take quite a bit to set up).

**Comment by jamesaoverton** [comment]
Yes, the two suggested options are <w3id.org> or <purl.obolibrary.org>.

**Comment by dr-shorthair** [comment]
> UCUM annotations with {} e.g. mg/mol{creat}. 

Note that {braces} are not part of the UCUM dataset per se. They are just available to add annotations that do not affect scaling. And yes, they almost always related to the aspect of semantics that elsewhere is called 'QuantityKind' or 'Parameter' or 'measurand'.

**Comment by kaiiam** [comment]
@dr-shorthair and @HajoRijgersberg see [metric_labels.csv](https://github.com/kaiiam/UO_revamp/blob/main/qname_processing/input_mappings/SI/metric_labels.csv) for a first pass at the collection of SI/metric symbols and labels for stage 1 of our plan above `SI only. Making use of the SI brochure for codes, not the UCUM codes.` Please let me know if you find any issues with this or can suggesting what's missing or next steps etc. 

In order to operate on SI codes I've written a first pass at the SI parser code [here](https://github.com/kaiiam/UO_revamp/blob/main/qname_processing/SI_parser.py) based on @jamesaoverton's work https://github.com/kaiiam/UO_revamp/pull/4. I wonder if we need to modify this so that not all metric units can be crossed with metric prefixes, e.g. (centi)(day)? Although `cd` will evaluate to candela not centi-day with the current script. 

example outputs (lists of python dictionaries parsed from the input strings. We can use these to convert back and forth to UCUM and assemble labels (better than the current regex  solution). 
```
m/s [{'type': 'metric', 'unit': 'm'}, {'operator': '/', 'type': 'metric', 'unit': 's'}]
s-1 [{'type': 'metric', 'unit': 's', 'exponent': -1}]
Gy2 [{'type': 'metric', 'unit': 'Gy', 'exponent': 2}]
°C [{'type': 'metric', 'unit': '°C'}]
′′ [{'type': 'metric', 'unit': '′′'}]
aau/aa/A [[{'prefix': 'a', 'type': 'metric', 'unit': 'au'}, {'operator': '/', 'prefix': 'a', 'type': 'metric', 'unit': 'a'}], {'operator': '/', 'type': 'metric', 'unit': 'A'}]
aSv/zS/dasr [[{'prefix': 'a', 'type': 'metric', 'unit': 'Sv'}, {'operator': '/', 'prefix': 'z', 'type': 'metric', 'unit': 'S'}], {'operator': '/', 'prefix': 'da', 'type': 'metric', 'unit': 'sr'}]
```

**Comment by dr-shorthair** [comment]
Good to see these specific tests executed. 

As [@jamesaoverton noted](https://github.com/kaiiam/UO_revamp/issues/2#issuecomment-796838374), UCUM did the work to resolve the ambiguities. But as a consequence does deviate from SI notation in a few places (because SI is slightly broken ;-) ). 

In our implementations it will be critical to stay clear about _which_ notation convention is in use at each point. (I have used the datatype `^^qudt:UCUMcs` on the UCUM codes fairly consistently in the RDF representation. )

**Comment by kaiiam** [comment]
@dr-shorthair yes absolutely, @jamesaoverton's thinking was to for the new unit system to have 2 prefixes one for SI e.g., `http://.../unit/SI_` and one for UCUM e.g., `http://.../unit/UCUM_` or something along those lines. Thoughts?

If we do something like then we say to users you can use either SI codes or UCUM codes (but not a mix) to make compound units, and the script would try to parse both (trying SI first if not try UCUM if not give a warning). @dr-shorthair does this seem reasonable? 

If we were to do something like that would we want to make the SI namespace **only** SI base, SI name and SI accepted units? Or do we want to include mentioned units too e.g. `dyne`, `calorie`, `bar` etc what about `curie` which is mentioned, but not SI accepted? Anything we don't include in the SI space would of course be usable within the UCUM space. Can @dr-shorthair and @HajoRijgersberg's give us your perspective about where to draw the line with "SI"? Current first pass is in [metric_labels.csv](https://github.com/kaiiam/UO_revamp/blob/main/qname_processing/input_mappings/SI/metric_labels.csv). Let me know what you think should change add remove etc.

**Comment by dr-shorthair** [comment]
> you can use either SI codes or UCUM codes (but not a mix) to make compound units, ... does this seem reasonable?

Yes. 

> Can @dr-shorthair and @HajoRijgersberg's give us your perspective about where to draw the line with "SI"? 

Not sure I can give an opinion on that. It is not a long list, though I note that some "should be avoided"

**Comment by kaiiam** [comment]
> It is not a long list, though I note that some "should be avoided"

Exactly my point do you @dr-shorthair and @HajoRijgersberg think the SI-only part of this should be really strict and minimal **only including the 7 SI base, the 22 SI name and short SI accepted units list?** Or should it have more than that? I'm thinking we go with the most conservative interpretation of SI accepted/approved list and punt everything else to the UCUM list. If so we would punt units like dyne, calorie, bar, curie, etc to the UCUM accessible list. Is this reasonable?

**Comment by jamesaoverton** [comment]
I agree with the conservative approach. We can't have any ambiguity, and we don't want to do the (difficult, error-prone) work of resolving ambiguity ourselves. UCUM has done that work. I think we can address @HajoRijgersberg's concerns by providing a pure SI solution for the most important parts of SI. We can use UCUM to handle the "should be avoided" metric edge cases, all the non-metric units, and find some sort of solution for non-units (`{annotations}`).

**Comment by HajoRijgersberg** [comment]
> Can @dr-shorthair and @HajoRijgersberg's give us your perspective about where to draw the line with "SI"?
> think the SI-only part of this should be really strict and minimal only including the 7 SI base, the 22 SI name and short SI accepted units list? 

I think both in the SI part and the UCUM part all possible units should appear, but in both parts their own symbols are used. In the UCUM part that means all symbols are unique (as far as I understand). In the SI part that means disambiguation is needed:
- a_(are)
- a_(year)
 
And something similar for (sub)multiples of are and year, e.g. 'ha_(are)' and 'ha_(year)'

> you can use either SI codes or UCUM codes (but not a mix) to make compound units, ... does this seem reasonable?

Yes.

**Comment by dr-shorthair** [comment]
Agree with the conservative approach. 
SI _the standard_ does not claim to be comprehensive. It's scope is just the ones in the SI Manual. 
UCUM OTOH does claim a bigger scope. 
We should respect the intentions of the custodians.

**Comment by kaiiam** [comment]
I think we've sorted many of the issues here and I'd suggest we move the discussion of IRIs forward to https://github.com/kaiiam/UO_revamp/issues/11.

**Comment by HajoRijgersberg** [comment]
> UCUM OTOH does claim a bigger scope [than SI].

The SI has been wide spread for decades if not centuries in all domains throughout the world. How can the scope of UCUM be bigger?
But I guess you're joking, and I let myself get fooled! :D

**Comment by kaiiam** [comment]
> How can the scope of UCUM be bigger?

No joke @dr-shorthair means there are literally more units that UCUM represents than SI does. SI has it's set of base units prefixed units and derived combos thereof. UCUM represents all that and terms from **additional** units systems imperial units, Averdupois units etc. 

UCUM has resolved these ambiguities and done most of the work already finding and making all these base units from various unit systems and allowing them to be used in their system via codes that get expressed in a finite state machine. I'd amazing work, we are really just creating a semantic-web wrapper around it, taking together pieces from all the best system OM, hopefully in the future dimention vectors from QUDT, and combining that with UCUM codes, creating the script to auto-generate all appropriate APs and giving it a dynamic server for all to use on the web.

**Comment by HajoRijgersberg** [comment]
Ah, but the number of units is not that important for a standard. What matters is who all have accepted the standard.
Now you are "just" making a wrapper around UCUM, where it could have been so much more!
You only have to comply a few symbols to the SI by disambiguating them differently.
But you're really underestimating your work! And I also mean that as a compliment!

**Comment by kaiiam** [comment]
> Now you are "just" making a wrapper around UCUM

Not "just" that, perhaps better to say it's aggregating everything we can find from existing systems into one while trying to break things (like SI) conventions as little as possible. 

> Where it could have been so much more!

What exactly do you propose then? I'm all ears for suggestions, but here it sounds to me like you are suggesting coming up with a new standard for codes and or labels separate from UCUM which somehow better fits the SI? I don't think we can do better with codes then they did while minimizing conflicts.

**Comment by HajoRijgersberg** [comment]
> while trying to break things (like SI) conventions as little as possible.

That's the thing with standardization: changing symbols is not breaking conventions as little as possible. A smaller change would be to leave the symbol as it is but writing something behind it in some kind of brackets, like ha_(hectare).

> suggesting coming up with a new standard for codes and or labels separate from UCUM which somehow better fits the SI? I don't think we can do better with codes then they did while minimizing conflicts.

We only have to change the are and year symbols back to their official symbols ('a'), with some disambiguation behind it, as far as I can see now. But I would have to take a look at the entire list of UCUM. I am thinking about taking that challenge, as I wrote in another thread, but it would take a significant amount of time and energy, so I would like to check with you and all of you if that effort would really be desired or that you (for other, maybe more political reasons) would still use the UCUM codes after all.

**Comment by kaiiam** [comment]
See my responses in https://github.com/kaiiam/UO_revamp/issues/11
